"""Wire protocol messages for the layercast metadata server.

Types are generated by betterproto from proto/layercast.proto.
Used by both the gRPC client (wrapper messages) and internal logic
(inner messages like PrepareModel, Prepared, etc.).

State machine (per pod session on the server):
  Connected ──PrepareModel──► Preparing ──ModelLoaded──► Ready
  Ready ─────ModelUnloaded──► Connected
  Ready ─────PrepareModel───► Preparing  (hot-swap)
  Ready ─────pod deleted───► cleanup    (crash protection via Pod watcher)
"""

from __future__ import annotations

import struct

from vllm_layercast.pb.layercast import (
    Error,
    IpcRequest,
    IpcResponse,
    ModelLoaded,
    ModelLoadedRequest,
    ModelLoadedResponse,
    ModelUnloaded,
    ModelUnloadedRequest,
    ModelUnloadedResponse,
    Ok,
    PeerNixlMd,
    PeerTransferAssignment,
    Prepared,
    PrepareModel,
    PrepareModelRequest,
    PrepareModelResponse,
    TensorInfo,
)

__all__ = [
    "Error",
    "IpcRequest",
    "IpcResponse",
    "ModelLoaded",
    "ModelLoadedRequest",
    "ModelLoadedResponse",
    "ModelUnloaded",
    "ModelUnloadedRequest",
    "ModelUnloadedResponse",
    "Ok",
    "PeerNixlMd",
    "PeerTransferAssignment",
    "Prepared",
    "PrepareModel",
    "PrepareModelRequest",
    "PrepareModelResponse",
    "TensorInfo",
    "encode",
    "decode_response",
]


def encode(msg: IpcRequest) -> bytes:
    """Serialize an IpcRequest to length-prefixed protobuf bytes."""
    payload = bytes(msg)
    return struct.pack(">I", len(payload)) + payload


def decode_response(data: bytes) -> IpcResponse:
    """Deserialize a daemon response from protobuf bytes."""
    return IpcResponse().parse(data)
