"""Wire protocol messages for the layercast daemon IPC.

All messages are length-prefixed protobuf: 4-byte big-endian length followed
by the protobuf payload. Types are generated by betterproto from
proto/layercast.proto.

State machine (per connection):
  Connected ──PrepareModel──► Preparing ──ModelLoaded──► Ready
  Ready ─────ModelUnloaded──► Connected
  Ready ─────PrepareModel───► Preparing  (hot-swap)
  Ready ─────EOF────────────► cleanup    (crash protection)
"""

from __future__ import annotations

import struct

from vllm_layercast.pb.layercast import (
    Error,
    IpcRequest,
    IpcResponse,
    ModelLoaded,
    ModelUnloaded,
    Ok,
    PeerNixlMd,
    PeerTransferAssignment,
    Prepared,
    PrepareModel,
    TensorInfo,
)

__all__ = [
    "Error",
    "IpcRequest",
    "IpcResponse",
    "ModelLoaded",
    "ModelUnloaded",
    "Ok",
    "PeerNixlMd",
    "PeerTransferAssignment",
    "Prepared",
    "PrepareModel",
    "TensorInfo",
    "encode",
    "decode_response",
]


def encode(msg: IpcRequest) -> bytes:
    """Serialize an IpcRequest to length-prefixed protobuf bytes."""
    payload = bytes(msg)
    return struct.pack(">I", len(payload)) + payload


def decode_response(data: bytes) -> IpcResponse:
    """Deserialize a daemon response from protobuf bytes."""
    return IpcResponse().parse(data)
