// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f deploy/external-crds/inferencepool.yaml --docs
// kopium version: 0.22.5
//
// Regenerate with: just kopium-inferencepool

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
    pub use std::collections::BTreeMap;
}
use self::prelude::*;

/// InferencePoolSpec defines the desired state of InferencePool
#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "inference.networking.x-k8s.io",
    version = "v1alpha2",
    kind = "InferencePool",
    plural = "inferencepools"
)]
#[kube(namespaced)]
#[kube(status = "InferencePoolStatus")]
#[kube(schema = "disabled")]
pub struct InferencePoolSpec {
    /// Extension configures an endpoint picker as an extension service.
    #[serde(rename = "extensionRef")]
    pub extension_ref: InferencePoolExtensionRef,
    /// Selector defines a map of labels to watch model server Pods
    /// that should be included in the InferencePool.
    pub selector: BTreeMap<String, String>,
    /// TargetPortNumber defines the port number to access the selected model server Pods.
    #[serde(rename = "targetPortNumber")]
    pub target_port_number: i32,
}

/// Extension configures an endpoint picker as an extension service.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct InferencePoolExtensionRef {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "failureMode"
    )]
    pub failure_mode: Option<InferencePoolExtensionRefFailureMode>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    pub name: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "portNumber"
    )]
    pub port_number: Option<i32>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum InferencePoolExtensionRefFailureMode {
    FailOpen,
    FailClose,
}

/// Status defines the observed state of InferencePool.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct InferencePoolStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent: Option<Vec<InferencePoolStatusParent>>,
}

/// PoolStatus defines the observed state of InferencePool from a Gateway.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct InferencePoolStatusParent {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition>>,
    #[serde(rename = "parentRef")]
    pub parent_ref: InferencePoolStatusParentParentRef,
}

/// GatewayRef indicates the gateway that observed state of InferencePool.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct InferencePoolStatusParentParentRef {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}
