# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: layercast.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    Dict,
    List,
    Optional,
)

import betterproto


@dataclass(eq=False, repr=False)
class PrepareModelRequest(betterproto.Message):
    pod_name: str = betterproto.string_field(1)
    pod_ip: str = betterproto.string_field(2)
    prepare: "PrepareModel" = betterproto.message_field(3)
    peer_discovery_timeout_s: Optional[int] = betterproto.uint32_field(
        4, optional=True, group="_peer_discovery_timeout_s"
    )


@dataclass(eq=False, repr=False)
class PrepareModelResponse(betterproto.Message):
    prepared: "Prepared" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ModelLoadedRequest(betterproto.Message):
    pod_name: str = betterproto.string_field(1)
    loaded: "ModelLoaded" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ModelLoadedResponse(betterproto.Message):
    ok: "Ok" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ModelUnloadedRequest(betterproto.Message):
    pod_name: str = betterproto.string_field(1)
    unloaded: "ModelUnloaded" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ModelUnloadedResponse(betterproto.Message):
    ok: "Ok" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class IpcRequest(betterproto.Message):
    prepare_model: "PrepareModel" = betterproto.message_field(1, group="msg")
    model_loaded: "ModelLoaded" = betterproto.message_field(2, group="msg")
    model_unloaded: "ModelUnloaded" = betterproto.message_field(3, group="msg")


@dataclass(eq=False, repr=False)
class PrepareModel(betterproto.Message):
    model_id: str = betterproto.string_field(1)
    revision: str = betterproto.string_field(2)
    tp_rank: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class ModelLoaded(betterproto.Message):
    agent_name: str = betterproto.string_field(1)
    nixl_md: bytes = betterproto.bytes_field(2)
    tensors: List["TensorInfo"] = betterproto.message_field(3)
    model_id: str = betterproto.string_field(4)
    files: List[str] = betterproto.string_field(5)
    tp_rank: int = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class ModelUnloaded(betterproto.Message):
    agent_name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class IpcResponse(betterproto.Message):
    prepared: "Prepared" = betterproto.message_field(1, group="msg")
    ok: "Ok" = betterproto.message_field(2, group="msg")
    error: "Error" = betterproto.message_field(3, group="msg")


@dataclass(eq=False, repr=False)
class Prepared(betterproto.Message):
    files: List[str] = betterproto.string_field(1)
    peers: List["PeerNixlMd"] = betterproto.message_field(2)
    weight_map: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    transfer_plan: List["PeerTransferAssignment"] = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class PeerNixlMd(betterproto.Message):
    agent_name: str = betterproto.string_field(1)
    nixl_md: bytes = betterproto.bytes_field(2)
    tensors: List["TensorInfo"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class TensorInfo(betterproto.Message):
    name: str = betterproto.string_field(1)
    addr: int = betterproto.uint64_field(2)
    size: int = betterproto.uint64_field(3)
    device_id: int = betterproto.uint32_field(4)
    dtype: str = betterproto.string_field(5)
    checksum: int = betterproto.uint64_field(6)


@dataclass(eq=False, repr=False)
class PeerTransferAssignment(betterproto.Message):
    agent_name: str = betterproto.string_field(1)
    nixl_md: bytes = betterproto.bytes_field(2)
    tensors: List["TensorInfo"] = betterproto.message_field(3)
    assigned_tensors: List[str] = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class Ok(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class Error(betterproto.Message):
    message: str = betterproto.string_field(1)
